name: Build GlitterBeam Fire TV APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install build tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Verify project files
        run: |
          pwd
          ls -la
          echo "----- app module -----"
          ls -la app
          echo "----- src/main -----"
          ls -la app/src/main || true

      - name: Download Gradle 8.6
        run: |
          curl -L https://services.gradle.org/distributions/gradle-8.6-bin.zip -o gradle.zip
          unzip -q gradle.zip
          chmod +x gradle-8.6/bin/gradle
          ./gradle-8.6/bin/gradle --version

      - name: Build Debug APK (verbose)
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          ./gradle-8.6/bin/gradle --no-daemon --stacktrace --info assembleDebug

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: glitterbeam-firetv-apk
          path: app/build/outputs/apk/debug/app-debug.apk
